sessions:
- startTime: ’04:00’
  endTime: ’04:29’
  rpm: ’010’
- startTime: ’04:30’
  endTime: ’04:55’
  rpm: ‘020’
- startTime: ’05:00’
  endTime: ’05:30’
  rpm: ‘010’
- startTime: ’05:30’
  endTime: ’05:55’
  rpm: ‘005’